backend/controllers/PointSaleController.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\models\PointSale;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\User;
use common\models\UserPointSale;
use common\models\Order ;
use common\models\Producer ;
use common\models\Distribution ;
use yii\helpers\Html;

/**
 * PointVenteController implements the CRUD actions for PointVente model.
 */
class PointSaleController extends BackendController 
{

    public function behaviors() 
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::hasAccessBackend();
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Liste les points de vente.
     * 
     * @return mixed
     */
    public function actionIndex() 
    {        
        $searchModel = new PointSaleSearch() ;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel, 
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Crée un point de vente.
     * 
     * @return mixed
     */
    public function actionCreate() 
    {
        $model = new PointSale();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->processPointProduction();
            $model->processRestrictedAccess();
            Distribution::linkPointSaleIncomingDistributions($model) ;
            return $this->redirect(['index']);
        } else {
            return $this->render('create', array_merge($this->initForm(), [
                'model' => $model,
            ]));
        }
    }

    /**
     * Modifie un point de vente.
     * 
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) 
    {
        $model = PointSale::find()
                ->with('userPointSale')
                ->where(['id' => $id])
                ->one();

        foreach ($model->userPointSale as $userPointSale) {
            $model->users[] = $userPointSale->id_user;
            $model->users_comment[$userPointSale->id_user] = $userPointSale->comment;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->processPointProduction();
            $model->processRestrictedAccess();
            Distribution::linkPointSaleIncomingDistributions($model) ;
            Yii::$app->getSession()->setFlash('success', 'Point de vente modifié.');
            return $this->redirect(['index']);
        } else {
            return $this->render('update', array_merge($this->initForm($id), [
                'model' => $model,
            ]));
        }
    }

    /**
     * Initialise le formulaire de création/modification.
     * 
     * @param integer $id
     * @return mixed
     */
    public function initForm($id = 0) 
    {
        $users = User::findBy()
            ->leftJoin('user_point_sale', 'user_point_sale.id_user = user.id AND user_point_sale.id_point_sale = :id_point_sale',[':id_point_sale' => $id])
            ->orderBy('user_point_sale.id_point_sale DESC, lastname ASC, name ASC')
            ->all();
        
        return [
            'users' => $users
        ];
    }

    /**
     * Supprime un point de vente et redirige vers la liste des points de vente.
     * 
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id, $confirm = false) 
    {  
        $pointSale = $this->findModel($id) ;
        
        if($confirm) {
            $pointSale->delete();
            UserPointSale::deleteAll(['id_point_sale' => $id]);
            PointSaleDistribution::deleteAll(['id_point_sale' => $id]) ;
            Order::updateAll(['id_point_sale' => 0], 'id_point_sale = :id_point_sale', [':id_point_sale' => $id]) ;
            Yii::$app->getSession()->setFlash('success', 'Point de vente <strong>'.Html::encode($pointSale->name).'</strong> supprimé.');
        } 
        else {
            Yii::$app->getSession()->setFlash('info', 'Souhaitez-vous vraiment supprimer le point de vente <strong>'.Html::encode($pointSale->name).'</strong> ? '
                    . Html::a('Oui',['point-sale/delete','id' => $id, 'confirm' => 1], ['class' => 'btn btn-default']).' '.Html::a('Non', ['point-sale/index'], ['class' => 'btn btn-default']));
        }
        
        return $this->redirect(['index']);
    }
    
    /**
     * Définit un point de vente par défaut.
     * 
     * @param integer $id
     */
    public function actionDefault($id) 
    {
        $pointSale = $this->findModel($id) ;
        if($pointSale) {
            PointSale::updateAll(['default' => 0], 'id_producer = :id_producer', [':id_producer' => GlobalParam::getCurrentProducerId()]) ;
            if(!$pointSale->default) {
                $pointSale->default = 1 ;
                $pointSale->save() ;
                Yii::$app->getSession()->setFlash('success', 'Point de vente <strong>'.Html::encode($pointSale->name).'</strong> défini par défaut.') ;
            }
            else {
                Yii::$app->getSession()->setFlash('success', 'Aucun point de vente défini par défaut') ;
            }
        }
        
        return $this->redirect(['index']);
    }

    /**
     * Recherche un point de vente en fonction de son ID.
     * 
     * @param integer $id
     * @return PointVente 
     * @throws NotFoundHttpException si le modèle n'est pas trouvé
     */
    protected function findModel($id) 
    {
        if (($model = PointSale::findOne($id)) !== null) {
            return $model;
        } 
        else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/point-sale/_form.php
<?php

/**
 * Copyright distrib (2018)
 *
 * contact@opendistrib.net
 *
 * Ce logiciel est un programme informatique servant à aider les producteurs
 * à distribuer leur production en circuits courts.
 *
 * Ce logiciel est régi par la licence CeCILL soumise au droit français et
 * respectant les principes de diffusion des logiciels libres. Vous pouvez
 * utiliser, modifier et/ou redistribuer ce programme sous les conditions
 * de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA
 * sur le site "http://www.cecill.info".
 *
 * En contrepartie de l'accessibilité au code source et des droits de copie,
 * de modification et de redistribution accordés par cette licence, il n'est
 * offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
 * seule une responsabilité restreinte pèse sur l'auteur du programme,  le
 * titulaire des droits patrimoniaux et les concédants successifs.
 *
 * A cet égard  l'attention de l'utilisateur est attirée sur les risques
 * associés au chargement,  à l'utilisation,  à la modification et/ou au
 * développement et à la reproduction du logiciel par l'utilisateur étant
 * donné sa spécificité de logiciel libre, qui peut le rendre complexe à
 * manipuler et qui le réserve donc à des développeurs et des professionnels
 * avertis possédant  des  connaissances  informatiques approfondies.  Les
 * utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
 * logiciel à leurs besoins dans des conditions permettant d'assurer la
 * sécurité de leurs systèmes et ou de leurs données et, plus généralement,
 * à l'utiliser et l'exploiter dans les mêmes conditions de sécurité.
 *
 * Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
 * pris connaissance de la licence CeCILL, et que vous en avez accepté les
 * termes.
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Producer;
use common\models\ProductPrice ;

/* @var $this yii\web\View */
/* @var $model backend\models\PointVente */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="point-sale-form">

        <?php $form = ActiveForm::begin(); ?>

        <div class="col-md-8">

                <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($model, 'locality')->textInput(['maxlength' => 255]) ?>
                <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>
                <?= $form->field($model, 'id_user', [
                        'template' => '{label} <a href="' . Yii::$app->urlManager->createUrl(['user/create']) . '" class="btn btn-xs btn-default">Nouvel utilisateur <span class="glyphicon glyphicon-plus"></span></a><div>{input}</div>{hint}',
                ])
                        ->dropDownList(
                                ArrayHelper::map(User::findBy()->orderBy('type DESC')->all(), 'user_id', function ($model) {
                                        if(strlen($model['name_legal_person'])) {
                                                return 'Personne morale / '.$model['name_legal_person'] ;
                                        }
                                        else {
                                                return $model['lastname'] . ' ' . $model['name'];
                                        }
                                }),
                                [
                                        'prompt' => '--',
                                ]
                        )->hint('Utilisé lors de la facturation'); ?>

                <?php
                $addHintCredit = '';
                if (!Producer::getConfig('credit')):
                        $addHintCredit = '<br /><strong>Attention, le système de Crédit est désactivé au niveau des ' . Html::a('paramètres globaux', ['producer/update']) . '.</strong>';
                endif;

                echo $form->field($model, 'credit')
                        ->checkbox()
                        ->hint('Cochez cette case si le client peut régler ses commandes via son compte <strong>Crédit</strong> pour ce point de vente.'
                                . $addHintCredit);
                ?>

                <?= $form->field($model, 'credit_functioning')
                        ->dropDownList([
                                '' => 'Paramètres globaux (' . Producer::$creditFunctioningArray[Producer::getConfig('credit_functioning')] . ')',
                                Producer::CREDIT_FUNCTIONING_OPTIONAL => Producer::$creditFunctioningArray[Producer::CREDIT_FUNCTIONING_OPTIONAL],
                                Producer::CREDIT_FUNCTIONING_MANDATORY => Producer::$creditFunctioningArray[Producer::CREDIT_FUNCTIONING_MANDATORY],
                                Producer::CREDIT_FUNCTIONING_USER => Producer::$creditFunctioningArray[Producer::CREDIT_FUNCTIONING_USER],
                        ], [])->hint(Producer::HINT_CREDIT_FUNCTIONING); ?>

                <?php /*$form->field($model, 'product_price_percent')
                        ->dropDownList(ProductPrice::percentValues(), [])->hint('Pourcentage appliqué aux prix de chaque produit dans ce point de vente.');*/ ?>


                <div id="delivery-days">
                        <h2>Jours de livraison</h2>
                        <?= $form->field($model, 'delivery_monday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_tuesday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_wednesday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_thursday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_friday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_saturday')->checkbox() ?>
                        <?= $form->field($model, 'delivery_sunday')->checkbox() ?>
                </div>
                <div class="clr"></div>

                <h2>Informations</h2>
                <?= $form->field($model, 'infos_monday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_tuesday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_wednesday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_thursday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_friday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_saturday')->textarea(['rows' => 3]) ?>
                <?= $form->field($model, 'infos_sunday')->textarea(['rows' => 3]) ?>
        </div>
        <div class="col-md-4">

                <?= $form->field($model, 'code')
                        ->label('Code d\'accès')
                        ->hint('Renseignez ce champs si vous souhaitez protéger ce point de vente par un code.')
                ?>


                <?= $form->field($model, 'restricted_access')
                        ->checkbox()
                        ->hint('Cochez cette case si seulement un groupe restreint d\'utilisateurs peuvent accéder à ce point de vente.<br />'
                                . 'Dans le cas des boîtes à pain, il vous est possible de spécifier un commentaire pour chaque utilisateur sélectionné afin de lui renseigner son numéro de boîte ou son code.') ?>
                <div id="users">
                        <?= Html::activeCheckboxList($model, 'users', ArrayHelper::map($users, 'user_id', function ($model_user, $defaultValue) use ($model) {
                                return Html::encode($model_user['lastname'] . ' ' . $model_user['name']) . '<br />'
                                        . Html::activeTextInput(
                                                $model,
                                                'users_comment[' . $model_user['user_id'] . ']',
                                                [
                                                        'class' => 'form-control commentaire',
                                                        'placeholder' => 'Commentaire',
                                                        'value' => (isset($model->users_comment[$model_user['user_id']])) ? Html::encode($model->users_comment[$model_user['user_id']]) : ''
                                                ]);
                        }), ['encode' => false, 'class' => '']) ?>
                </div>
        </div>
        <div class="clr"></div>

        <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Ajouter' : 'Modifier', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

</div>

backend/views/point-sale/create.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

use yii\helpers\Html;


$this->setTitle('Ajouter un point de vente') ;
$this->addBreadcrumb(['label' => 'Points de vente', 'url' => ['index']]) ;
$this->addBreadcrumb('Ajouter') ;

?>

<div class="point-sale-create">
    <?= $this->render('_form', [
        'model' => $model,
        'users' => $users,
    ]) ?>
</div>

backend/views/point-sale/index.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\PointVenteUser ;

$this->setTitle('Points de vente') ;
$this->addBreadcrumb($this->getTitle()) ;
$this->addButton(['label' => 'Nouveau point de vente <span class="glyphicon glyphicon-plus"></span>', 'url' => 'point-sale/create', 'class' => 'btn btn-primary']) ;

?>

<div class="point-sale-index">
    <?= GridView::widget([
        'filterModel' => $searchModel, 
        'dataProvider' => $dataProvider,
        'columns' => [
            'name',
            'locality',
            [
                'attribute' => 'delivery',
                'label' => 'Livraison',
                'filter' => [
                    'monday' => 'Lundi',
                    'tuesday' => 'Mardi',
                    'wednesday' => 'Mercredi',
                    'thursday' => 'Jeudi',
                    'friday' => 'Vendredi',
                    'saterday' => 'Samedi',
                    'sunday' => 'Dimanche',
                ],
                'value' => function($model) {
                    return $model->getStrDeliveryDays() ;
                }
            ],
            [
                'attribute' => 'access_type',
                'label' => 'Accès',
                'filter' => [
                    'open' => 'Ouvert',
                    'code' => 'Code',
                    'restricted_access' => 'Accès restreint'
                ],
                'format' => 'raw',
                'value' => function($model) {
                    $count = UserPointSale::find()->where(['id_point_sale' => $model->id])->count(); 
                    $html = '' ;
                    if($model->restricted_access)
                    {
                        $html .= '<span class="glyphicon glyphicon-lock"></span> ' ;
                        if($count == 1)
                        {
                            $html .= '1 utilisateur' ;
                        }
                        else {
                           $html .= $count.' utilisateurs' ;
                        }
                    }
                    
                    if(strlen($model->code))
                    {
                        if(strlen($html)) $html .= '<br />' ;
                        $html .= 'Code : <strong>'.Html::encode($model->code).'</strong>' ;
                    }
                    
                    return $html ;
                    
                }
            ],
            [
                'attribute' => 'credit',
                'label' => 'Crédit',
                'format' => 'raw',
                'value' => function($model) {
                    if($model->credit) {
                        return '<span class="glyphicon glyphicon-euro"></span>' ;
                    }
                        
                    return '' ;
                }
            ],
            [
                'attribute' => 'default',
                'label' => 'Par défaut',
                'format' => 'raw',
                'contentOptions' => ['class' => 'td-default'],
                'value' => function($model) {
                    if($model->default) {
                        return Html::a('<span class="glyphicon glyphicon-star"></span>', ['point-sale/default','id' => $model->id], [
                            'title' => Yii::t('app', 'Point de vente par défaut'), 'class' => 'btn btn-default'
                        ]);
                    }
                    else 
                    {
                        return Html::a('<span class="glyphicon glyphicon-star-empty"></span>', ['point-sale/default','id' => $model->id], [
                            'title' => Yii::t('app', 'Point de vente par défaut'), 'class' => 'btn btn-default'
                        ]);
                    }
                    
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'headerOptions' => ['class' => 'column-actions'],
                'contentOptions' => ['class' => 'column-actions'],
                'buttons' => [
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'title' => Yii::t('app', 'Modifier'), 'class' => 'btn btn-default'
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                    'title' => Yii::t('app', 'Supprimer'), 'class' => 'btn btn-default'
                        ]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/point-sale/update.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

use yii\helpers\Html;

$this->setTitle('Modifier un point de vente') ;
$this->addBreadcrumb(['label' => 'Points de vente', 'url' => ['index']]) ;
$this->addBreadcrumb(['label' => Html::encode($model->name), 'url' => ['update', 'id' => $model->id]]) ;
$this->addBreadcrumb('Modifier') ;

?>

<div class="point-sale-update">
    <?= $this->render('_form', [
        'model' => $model,
        'users' => $users
    ]) ?>
</div>