frontend/controllers/SiteController.php
<?php

/**
 * Copyright distrib (2018)
 *
 * contact@opendistrib.net
 *
 * Ce logiciel est un programme informatique servant à aider les producteurs
 * à distribuer leur production en circuits courts.
 *
 * Ce logiciel est régi par la licence CeCILL soumise au droit français et
 * respectant les principes de diffusion des logiciels libres. Vous pouvez
 * utiliser, modifier et/ou redistribuer ce programme sous les conditions
 * de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA
 * sur le site "http://www.cecill.info".
 *
 * En contrepartie de l'accessibilité au code source et des droits de copie,
 * de modification et de redistribution accordés par cette licence, il n'est
 * offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
 * seule une responsabilité restreinte pèse sur l'auteur du programme,  le
 * titulaire des droits patrimoniaux et les concédants successifs.
 *
 * A cet égard  l'attention de l'utilisateur est attirée sur les risques
 * associés au chargement,  à l'utilisation,  à la modification et/ou au
 * développement et à la reproduction du logiciel par l'utilisateur étant
 * donné sa spécificité de logiciel libre, qui peut le rendre complexe à
 * manipuler et qui le réserve donc à des développeurs et des professionnels
 * avertis possédant  des  connaissances  informatiques approfondies.  Les
 * utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
 * logiciel à leurs besoins dans des conditions permettant d'assurer la
 * sécurité de leurs systèmes et ou de leurs données et, plus généralement,
 * à l'utiliser et l'exploiter dans les mêmes conditions de sécurité.
 *
 * Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
 * pris connaissance de la licence CeCILL, et que vous en avez accepté les
 * termes.
 */

namespace frontend\controllers;

use Yii;
use common\models\Product;
use common\models\LoginForm;
use common\models\Producer;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use common\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Html;
use frontend\controllers\FrontendController;
use common\models\UserProducer;
use dosamigos\leaflet\types\LatLng;
use dosamigos\leaflet\layers\Marker;
use dosamigos\leaflet\layers\TileLayer;
use dosamigos\leaflet\LeafLet;
use dosamigos\leaflet\widgets\Map;

/**
 * Site controller
 */
class SiteController extends FrontendController
{

        /**
         * @inheritdoc
         */
        public function behaviors()
        {
                return [
                        'access' => [
                                'class' => AccessControl::className(),
                                'only' => ['logout', 'signup'],
                                'rules' => [
                                        [
                                                'actions' => ['signup'],
                                                'allow' => true,
                                                'roles' => ['?'],
                                        ],
                                        [
                                                'actions' => ['logout'],
                                                'allow' => true,
                                                'roles' => ['@'],
                                        ],
                                ],
                        ],
                        'verbs' => [
                                'class' => VerbFilter::className(),
                                'actions' => [
                                        'logout' => ['get'],
                                ],
                        ],
                ];
        }

        /**
         * @inheritdoc
         */
        public function actions()
        {
                return [
                        'captcha' => [
                                'class' => 'yii\captcha\CaptchaAction',
                                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                        ],
                ];
        }

        /**
         * Affiche la page d'erreur.
         *
         * @return mixed
         */
        public function actionError()
        {
                $exception = Yii::$app->errorHandler->exception;

                if ($exception->getMessage() == 'Producteur introuvable' || Yii::$app->getRequest()->getQueryParam('producer_not_found')) {
                        return $this->render('error-404-producer', ['exception' => $exception]);
                }

                if ($exception !== null) {
                        return $this->render('error', ['exception' => $exception]);
                }
        }

        /**
         * Affiche la page d'accueil.
         *
         * @return mixed
         */
        public function actionIndex()
        {
                return $this->render('index', [
                        'producerDemoAccount' => Producer::getDemoAccount()
                ]);
        }

        /**
         * Liste les producteurs utilisant la plateforme.
         *
         * @return mixed
         */
        public function actionProducers()
        {
                $dataProviderProducers = new ActiveDataProvider([
                        'query' => Producer::find()
                                ->where([
                                        'active' => true,
                                ])
                                ->orderBy('name ASC'),
                        'pagination' => [
                                'pageSize' => 100,
                        ],
                ]);

                return $this->render('producers', [
                        'dataProviderProducers' => $dataProviderProducers
                ]);
        }

        /**
         * Affiche les mentions légales.
         *
         * @return mixed
         */
        public function actionMentions()
        {
                return $this->render('mentions');
        }

        /**
         * Affiche la page de connexion et traite le formulaire de connexion.
         *
         * @return mixed
         */
        public function actionLogin()
        {
                if (!\Yii::$app->user->isGuest) {
                        return Yii::$app->getResponse()->redirect(['site/index']);
                }

                $model = new LoginForm();
                if ($model->load(Yii::$app->request->post()) && $model->login()) {
                        $returnUrl = Yii::$app->request->get('return_url');
                        if ($returnUrl) {
                                return $this->redirect($returnUrl);
                        } else {
                                $userProducerArray = UserProducer::find()
                                        ->with(['producer'])
                                        ->where(['id_user' => User::getCurrentId(), 'active' => 1, 'bookmark' => 1])
                                        ->all();

                                if ($userProducerArray && is_array($userProducerArray) && count($userProducerArray) == 1) {
                                        return $this->redirect(Yii::$app->urlManagerProducer->createAbsoluteUrl(['site/index', 'slug_producer' => $userProducerArray[0]->producer->slug]));
                                } else {
                                        return $this->goBack();
                                }
                        }
                } else {
                        return $this->render('@frontend/views/site/login', [
                                'model' => $model,
                        ]);
                }
        }

        /**
         * Déconnecte l'utilisateur.
         *
         * @return mixed
         */
        public function actionLogout()
        {
                Yii::$app->user->logout();
                return $this->goHome();
        }

        /**
         * Affiche la page de contact et traite le formulaire s'il est soumis.
         *
         * @return mixed
         */
        public function actionContact()
        {
                $model = new ContactForm();
                if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                        if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                                Yii::$app->session->setFlash('success', 'Votre message a bien été envoyé. Nous vous répondrons dès que possible.');
                        } else {
                                Yii::$app->session->setFlash('error', 'Il y a eu une erreur lors de l\'envoi de votre message.');
                        }

                        return $this->refresh();
                } else {
                        return $this->render('contact', [
                                'model' => $model,
                        ]);
                }
        }

        /**
         * Affiche la page d'inscription et traite son formulaire.
         *
         * @return mixed
         */
        public function actionSignup()
        {
                $model = new SignupForm();
                if ($model->load(Yii::$app->request->post())) {
                        $user = $model->signup();
                        if ($user) {
                                if (Yii::$app->getUser()->login($user)) {
                                        if ($model->option_user_producer == 'producer') {
                                                $this->redirect(Yii::$app->urlManagerBackend->createAbsoluteUrl(['site/index']));
                                        } else {
                                                $producer = Producer::findOne($model->id_producer);
                                                if ($producer) {

frontend/views/site/_prices_producer.php
<?php 

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

?>

<!-- tarifs -->
<div class="modal fade" id="modal-prices" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Tarifs</h4>
      </div>
      <div class="modal-body">
          <p><em>distrib</em> fonctionne grâce à un système d'abonnement à <strong>prix libre</strong>.
          Chaque producteur définit lui-même le prix mensuel (HT) de son abonnement à la plateforme, selon son intérêt et le soutien qu'il veut apporter. Ce montant est modifiable à tout moment dans la section <em>Mon abonnement</em> de l'interface d'administration.</p>
          <p>Toutes les demandes de formation ou de développement spécifique feront l'objet d'un devis.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

frontend/views/site/cgv.php
<?php 
/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

$this->setTitle('Conditions générales de service') ;
$this->setMeta('description', 'Nous vous présentons ici les conditions selon lesquelles nous vous proposons nos offres de service.') ;

?>

<div class="content-text">
    
<h1>Conditions générales de service</h1>

<?= $this->render('_cgv_content'); ?>

</div>

frontend/views/site/credit.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

$this->setTitle('Crédit') ;
$this->setMeta('description','Présentation de la fonctionnalité "Crédit" de la plateforme.') ;

?>

<div class="container content-text">
    <div class="content">
        <h1>Le Crédit</h1>
        <p>Le <em>Crédit</em> est un compte prépayé qui vous permet de régler
            vos commandes sur le site <strong>distrib</strong>. Ainsi vous
            n'avez pas à payer chez votre producteur à chaque fois que vous y 
            récupérez une commande.</p>
        <p>Pour créditer votre compte, rien de plus simple. Il vous suffit de vous
        rendre chez votre producteur et de régler la somme que vous souhaitez créditer.
        Le producteur se chargera de mettre à jour votre <em>Crédit</em>
        en ligne.</p>
        <p>Lors de vos prochaines commandes, vous aurez juste à indiquer que vous souhaitez
            payer avec votre <em>Crédit</em> et votre compte sera automatiquement débité.</p>
    </div>
</div>

frontend/views/site/error-404-producer.php
<?php 

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

$this->setTitle('Producteur introuvable') ;
$this->setMeta('description','Le producteur que vous recherchez est introuvable.') ;

?>

<div class="site-error">

    <h1>Producteur introuvable</h1>

    <div class="alert alert-danger">
        Le producteur que vous recherchez est introuvable.
    </div>

    <p><?= Html::a("&lt; Retour à l'accueil", ['site/index']) ?> - <?= Html::a("Liste des producteurs", ['site/producers']) ?></p>
    
</div>

frontend/views/site/error.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->setTitle($exception->getName());
$this->setMeta('description', 'Oups ! Une erreur est survenue.') ;

?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($exception->getMessage())) ?>
    </div>

    <p><?= Html::a("Retour à l'accueil", ['site/index']) ?></p>
    
</div>

frontend/views/site/index.php
<?php

/** 
Copyright distrib (2018) 

contact@opendistrib.net

Ce logiciel est un programme informatique servant à aider les producteurs 
à distribuer leur production en circuits courts. 

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.
*/

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

use dosamigos\leaflet\types\LatLng;
use dosamigos\leaflet\layers\Marker;
use dosamigos\leaflet\layers\TileLayer;
use dosamigos\leaflet\LeafLet;
use dosamigos\leaflet\widgets\Map;

use common\helpers\Url ;

$this->setTitle('Logiciel libre de distribution alimentaire en circuit court') ;
$this->setMeta('description', 'Simplifiez la distribution de vos produits en circuit court grâce à des outils web adaptés.') ;

?>

<div id="presentation">
    <div id="presentation-distrib">
        <h1><span>Logiciel libre<br />
                de distribution alimentaire<br />
            en circuit court</span></h1>
        <p>simple, ouvert et participatif</p>
    </div>
    <div id="row-users-producers">
        <div class="col-md-6 producer">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <img class="img" src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/cagette.png" id="img-producer" />
                        <span class="the-title">Producteurs</span>
                    </h2>
                </div>
                <div class="panel-body">
                    <p class="presentation">Simplifiez la distribution de vos produits<br /> avec des outils adaptés.</p>
                    <a class="btn btn-primary" href="<?= Yii::$app->urlManagerFrontend->createUrl(['site/signup']) ; ?>"><span class="glyphicon glyphicon-user"></span> Je crée mon espace</a>
                    <!--<?php if($producerDemoAccount) : ?><a class="btn btn-default" href="<?= Yii::$app->urlManagerFrontend->createUrl(['site/producer', 'id' => $producerDemoAccount->id]) ; ?>"><span class="glyphicon glyphicon-blackboard"></span> Démonstration</a><?php endif; ?>-->
                    <a class="btn btn-default" href="<?= Yii::$app->urlManagerFrontend->createUrl(['site/contact']) ; ?>"><span class="glyphicon glyphicon-info-sign"></span> Demande d'informations</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 users">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <img class="img" src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/users.png" id="img-users" />
                        <span class="the-title">Clients</span>
                    </h2>
                </div>
                <div class="panel-body">
                    <p class="presentation">Réservez vos produits en ligne et récupérez votre commande
                    chez votre producteur ou dans un dépôt près de chez vous.</p>    
                    <a class="btn btn-primary" href="<?= Yii::$app->urlManagerFrontend->createUrl(['site/producers']) ; ?>"><span class="glyphicon glyphicon-search"></span> Je recherche un producteur</a>
                </div>
            </div>
        </div>
        <div class="clr"></div>
    </div>
    <?php if(Yii::$app->user->isGuest && YII_ENV == 'demo'): ?>
    <div class="row" id="row-signup">
        <a class="btn btn-primary btn-lg" href="<?= Url::env('prod','frontend'); ?>"><span class="glyphicon glyphicon-circle-arrow-left"></span> Retour sur le site</a>
    </div> 
    <?php endif; ?>
    
    <div id="row-functionalities-rates">
        <div class="panel panel-default" id="block-functionnalities">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <span class="glyphicon glyphicon-cog"></span> <span class="the-title">Fonctionnalités</span>
                </h2>
            </div>
            <div class="panel-body">
                <div class="block block-order col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/order.png" />
                    <p>Prise de commande en ligne automatisée avec génération d'un récapitulatif par jour de distribution.</p>
                    <div class="clr"></div>
                </div>
                <div class="block block-payment col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/payment.png" />
                    <p>Système de crédit permettant la comptabilisation des paiements.</p>
                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
                <div class="block block-points-sale-products col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/map-marker.png" />
                    <p>Gestion des différents points de vente et produits.</p>
                    <div class="clr"></div>
                </div>
                <div class="block block-subscriptions col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/subscription.png" />
                    <p>Gestion des abonnement.</p>
                    <div class="clr"></div>
                </div>
                <div class="clr"></div>
                <div class="block block-communication col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/megaphone.png" />
                    <p>Communication simplifiée avec les clients.</p>
                    <div class="clr"></div>
                </div>
                <div class="block block-evolution col-md-6">
                    <img src="<?= Yii::$app->urlManager->getBaseUrl(); ?>/img/idea.png" />
                    <p><a href="<?= Yii::$app->urlManager->createUrl(['site/contact']) ?>">Proposez-nous</a> vos idées afin de faire évoluer l'outil !</p>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
        <div class="panel panel-default" id="block-rates">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <span class="glyphicon glyphicon-euro"></span> <span class="the-title">Tarifs</span>
                </h2>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th colspan="2">Producteurs</th>
                            <th>Clients</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Abonnement mensuel</td>
                            <td><strong>Prix libre</strong></td>
                            <td><strong>Gratuit</strong></td>
                        </tr>
                        <tr>
                            <td>Formation & aide à la mise en place</td>
                            <td><strong>30 € HT / heure</strong></td>
                            <td>Possibilité de don<br />lors de la commande</td>
                        </tr>
                        <tr>
                            <td>Développement spécifique</td>
                            <td><strong>Sur devis</strong></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="clr"></div>
</div>

<!-- Tarifs -->
<?= $this->render('_prices_producer'); ?>